Added check for street prefix "ul", "ulica"
Zaczero/osm-addr-bot pull request #14
Opened 2024-04-16 17:10 UTC by kubahaha

As pointed in issue #5  - added check for prefix `ul` / `ulica`

Exemplary tagging to be reported as error:

```
highway=residential
name=ul. Główna
```

2024-04-16 20:34 UTC, Zaczero requested changes

2024-04-16 20:34 UTC, Zaczero commented on checks.py
> +                extra="Nazwa ulicy nie powinna zaczynać się od 'ul.', 'ulica ' itp."
```suggestion
                extra="Nazwa ulicy nie powinna zaczynać się od 'ul.', 'ulica' itp. "
```

2024-04-16 20:34 UTC, Zaczero commented on checks.py
> +STREET_NAME_BAD_PREFIX = re.compile(r'^ul(ica)?\.? ')
```suggestion
STREET_NAME_BAD_PREFIX = re.compile(r'^ul(ica)?\.? ', re.IGNORECASE)
```

Przy okazji można wychwycić Ul. UL. itp.

2024-04-16 21:36 UTC, kubahaha commented on checks.py
> +STREET_NAME_BAD_PREFIX = re.compile(r'^ul(ica)?\.? ')
Nie mam pojęcia czemu o tym zapomniałem, oczywiście masz rację.

2024-04-17 10:50 UTC, Zaczero approved these changes

2024-04-17 10:51 UTC, merged